name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x', '18.x', '20.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install
        run: npm ci
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 1
      - name: Lint
        if: matrix.node-version == '20.x'
        run: npm run lint
      - name: Types
        if: matrix.node-version == '20.x'
        run: node_modules/.bin/tsc
      - name: Test Node
        run: npm run test:node
      - name: Test Browser
        if: matrix.node-version == '20.x'
        run: |
          export PUPPETEER_EXECUTABLE_PATH=$(which google-chrome-stable)
          npm run test:browser
